name: Build Binaries

env:
  FREETYPE_VERSION: 2.12.1
  LUA_VERSION: 5.1.5
  OPENALSOFT_VERSION: 1.22.2
  SDL2_VERSION: 2.26.1

on:
  push:
    branches:
      - master
      - openal

jobs:
  linux-x64:
    name: Linux (x64)
    runs-on: ubuntu-20.04
    container: centos:centos7
    steps:
      - name: Install Dependencies
        run: |
          chown -R $(id -u):$(id -g) $PWD
          yum -y install https://repo.ius.io/ius-release-el7.rpm centos-release-scl scl-utils
          yum -y install devtoolset-8 cmake3 bzip2 patch
          yum -y install alsa-lib-devel portaudio-devel pulseaudio-libs-devel libsoundio-devel
          yum -y install libXext-devel libX11-devel mesa-libGL-devel mesa-libGLU-devel libXrender-devel libXrandr-devel libXcursor-devel libXinerama-devel libXi-devel
          mkdir -p artifacts/x64
      - name: OpenAL Soft
        run: |
          source /opt/rh/devtoolset-8/enable
          curl -s -L -O https://openal-soft.org/openal-releases/openal-soft-${OPENALSOFT_VERSION}.tar.bz2
          tar xf openal-soft-${OPENALSOFT_VERSION}.tar.bz2
          cd openal-soft-${OPENALSOFT_VERSION}/build
          cmake3 .. -DBUILD_SHARED_LIBS=true -DCMAKE_BUILD_TYPE=Release
          cmake3 --build .
          cp libopenal.so ../../artifacts/x64/soft_oal.so
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linux (x64)
          path: artifacts
  linux-arm64:
    runs-on: ubuntu-20.04
    name: Linux (arm64)
    steps:
      - name: OpenAL Soft
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu18.04
          shell: /bin/sh
          setup: |
            mkdir -p "${PWD}/artifacts/arm64"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          env: |
            OPENALSOFT_VERSION: ${{ env.OPENALSOFT_VERSION }}
          run: |
            apt-get update -q -y
            apt-get install -y build-essential curl cmake libasound2-dev portaudio19-dev libpulse-dev
            curl -s -L -O https://openal-soft.org/openal-releases/openal-soft-${OPENALSOFT_VERSION}.tar.bz2
            tar xf openal-soft-${OPENALSOFT_VERSION}.tar.bz2
            cd openal-soft-${OPENALSOFT_VERSION}/build
            cmake .. -DBUILD_SHARED_LIBS=true -DCMAKE_BUILD_TYPE=Release
            cmake --build .
            cp libopenal.so /artifacts/arm64/soft_oal.so
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linux (arm64)
          path: artifacts